#!/bin/bash

DATASET=uspto_50k
SAVENAME=Model0
VOCAB=uspto_50k
SEED=17
K=4
KERNEL=spd
BSZ=64
TOKENLIM=0
D_MODEL=256
D_FILTER=2048
ENC_LAYER=6
DEC_LAYER=8
DROP=0.3
TASK=dualtask
ETASK=retrosynthesis
EVAL_START=100000
EVAL_STEP=2000
T=1.0
BEAM_GROUP=1
K_FILTER=0
P_FILTER=0.0
OPTIM=AdamW
LRSD=cosine
FFN=vanilla
NORM=rmsnorm
AUG_N=5

python train.py \
    --dataset_name="$DATASET" \
    --save_name="$SAVENAME" \
    --vocab_name="$VOCAB" \
    --seed="$SEED" \
    --K="$K" \
    --kernel="$KERNEL" \
    --batch_size="$BSZ" \
    --token_limit="$TOKENLIM" \
    --d_model="$D_MODEL" \
    --d_ff="$D_FILTER" \
    --enc_layer="$ENC_LAYER" \
    --dec_layer="$DEC_LAYER" \
    --dropout="$DROP" \
    --mode="train" \
    --task="$TASK" \
    --eval_task="$ETASK" \
    --epochs=1000 \
    --steps=150000 \
    --accum_count=2 \
    --lr_factor=1.0 \
    --max_lr=3e-4 \
    --min_lr=1e-6 \
    --warmup=10000 \
    --end_step=150000 \
    --gamma=2.0 \
    --train_eval \
    --eval_start="$EVAL_START" \
    --eval_step="$EVAL_STEP" \
    --split_data_len=0 \
    --T="$T" \
    --beam_group="$BEAM_GROUP" \
    --top_k="$K_FILTER" \
    --top_p="$P_FILTER" \
    --optimizer="$OPTIM" \
    --lrschedule="$LRSD" \
    --ffn_type="$FFN" \
    --norm_type="$NORM" \
    --augment_N="$AUG_N"



#    --dataset_name="uspto_50k"
#    --save_name="Model0"
#    --vocab_name="uspto_50k"
#    --seed=17
#    --K=4
#    --kernel="spd"
#    --batch_size=64
#    --token_limit=0
#    --d_model=256
#    --d_ff=2048
#    --enc_layer=6
#    --dec_layer=8
#    --dropout=0.3
#    --mode="train"
#    --task="dualtask"
#    --eval_task="retrosynthesis"
#    --epochs=1000
#    --steps=150000
#    --accum_count=2
#    --lr_factor=1.0
#    --max_lr=3e-4
#    --min_lr=1e-6
#    --warmup=10000
#    --end_step=150000
#    --gamma=2.0
#    --train_eval
#    --eval_start=100000
#    --eval_step=2000
#    --split_data_len=0
#    --T=1.0
#    --beam_group=1
#    --top_k=0
#    --top_p=0.0
#    --optimizer="AdamW"
#    --lrschedule="cosine"
#    --ffn_type="vanilla"
#    --norm_type="rmsnorm"
#    --augment_N=5